name: Feature request
description: Suggest an idea or improvement for the Encoding Helper
body:
  - type: textarea
    id: solution
    attributes:
      label: Describe what you would like
      description: A clear and concise description of what you want to be improved.
    validations:
      required: true
